### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "5961924410",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "6588922787",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "24576b821bd24a1d982029f4293da22a",
  "accountNumber": "6588922787",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/92271146409d491eb26b74624a66d68a
